### ISSUE TITLE
Allowing PHPStan 2.0 to be used

### ISSUE THREAD

**Issue by menno-ll** [zorac/phpstan-php-di#1]
About a month ago, PHPStan released it's new version, 2.0.

Due to the current version constraints defined in composer.json, it's not possible to currently use PHPStan 2.0+.

After testing some myself, i think it should be possible to upgrade only be modifying the composer.json.

**Comment by zorac** [comment]
Thanks! That worked against one of my projects. I've published version 1.0.1 to packagist.

**Comment by menno-ll** [comment]
Awesome 🥳 , thank you for the swift reply.
Happy holidays! 🎅
